### ISSUE TITLE
Тип трансформации по умолчанию проставляется Spark2

### ISSUE THREAD

**Issue by arch7tect** [neoflex-consulting/datagram#1]
Нужно придумать, что с этим делать, при этом,
-как-то поддержать старые инсталляции, чтобы при переходе на новые версии DG трансформации создавались по старому
-на новых инсталляциях проставлялся тип, соответствующий рантайму

может ввести такой же тип в Livy?

**Comment by authent1c** [comment]
По дефолту (если не заполнено) выставляет версия которая содержится в номере билда
например mserver-spark2-2.0.0-SNAPSHOT будет выставлена версия сборки для spark2

**Comment by arch7tect** [comment]
![2021-04-02_16-15-50](https://user-images.githubusercontent.com/4629199/113418751-c0ac5e80-93ce-11eb-81ed-d6249cb0b674.png)

**Comment by arch7tect** [comment]
что-то пошло не так

**Comment by authent1c** [comment]
Мой косяк, постараюсь поправить в понедельник

**Comment by authent1c** [comment]
Пофикшено в 3f05bf61fcc3c190bdf8d44aa1906e915f92be58
